/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package cn.superid.webapp.notice.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.EncodingUtils;

import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import javax.annotation.Generated;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2016-12-22")
public class Msg implements org.apache.thrift.TBase<Msg, Msg._Fields>, java.io.Serializable, Cloneable, Comparable<Msg> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Msg");

  private static final org.apache.thrift.protocol.TField _ID_FIELD_DESC = new org.apache.thrift.protocol.TField("_id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("type", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField FR_UID_FIELD_DESC = new org.apache.thrift.protocol.TField("frUid", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField TO_UID_FIELD_DESC = new org.apache.thrift.protocol.TField("toUid", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField RID_FIELD_DESC = new org.apache.thrift.protocol.TField("rid", org.apache.thrift.protocol.TType.I64, (short)5);
  private static final org.apache.thrift.protocol.TField AID_FIELD_DESC = new org.apache.thrift.protocol.TField("aid", org.apache.thrift.protocol.TType.I64, (short)6);
  private static final org.apache.thrift.protocol.TField TO_RID_FIELD_DESC = new org.apache.thrift.protocol.TField("toRid", org.apache.thrift.protocol.TType.I64, (short)7);
  private static final org.apache.thrift.protocol.TField FR_RID_FIELD_DESC = new org.apache.thrift.protocol.TField("frRid", org.apache.thrift.protocol.TType.I64, (short)8);
  private static final org.apache.thrift.protocol.TField SUB_FIELD_DESC = new org.apache.thrift.protocol.TField("sub", org.apache.thrift.protocol.TType.I32, (short)9);
  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)10);
  private static final org.apache.thrift.protocol.TField CONTENT_FIELD_DESC = new org.apache.thrift.protocol.TField("content", org.apache.thrift.protocol.TType.STRING, (short)11);
  private static final org.apache.thrift.protocol.TField TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("time", org.apache.thrift.protocol.TType.I64, (short)12);
  private static final org.apache.thrift.protocol.TField INDEX_FIELD_DESC = new org.apache.thrift.protocol.TField("index", org.apache.thrift.protocol.TType.I32, (short)13);
  private static final org.apache.thrift.protocol.TField GA_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("gaId", org.apache.thrift.protocol.TType.I64, (short)14);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MsgStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MsgTupleSchemeFactory());
  }

  public String _id; // optional
  public int type; // optional
  public long frUid; // optional
  public long toUid; // optional
  public long rid; // optional
  public long aid; // optional
  public long toRid; // optional
  public long frRid; // optional
  public int sub; // optional
  public String name; // optional
  public String content; // optional
  public long time; // optional
  public int index; // optional
  public long gaId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    _ID((short)1, "_id"),
    TYPE((short)2, "type"),
    FR_UID((short)3, "frUid"),
    TO_UID((short)4, "toUid"),
    RID((short)5, "rid"),
    AID((short)6, "aid"),
    TO_RID((short)7, "toRid"),
    FR_RID((short)8, "frRid"),
    SUB((short)9, "sub"),
    NAME((short)10, "name"),
    CONTENT((short)11, "content"),
    TIME((short)12, "time"),
    INDEX((short)13, "index"),
    GA_ID((short)14, "gaId");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // _ID
          return _ID;
        case 2: // TYPE
          return TYPE;
        case 3: // FR_UID
          return FR_UID;
        case 4: // TO_UID
          return TO_UID;
        case 5: // RID
          return RID;
        case 6: // AID
          return AID;
        case 7: // TO_RID
          return TO_RID;
        case 8: // FR_RID
          return FR_RID;
        case 9: // SUB
          return SUB;
        case 10: // NAME
          return NAME;
        case 11: // CONTENT
          return CONTENT;
        case 12: // TIME
          return TIME;
        case 13: // INDEX
          return INDEX;
        case 14: // GA_ID
          return GA_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TYPE_ISSET_ID = 0;
  private static final int __FRUID_ISSET_ID = 1;
  private static final int __TOUID_ISSET_ID = 2;
  private static final int __RID_ISSET_ID = 3;
  private static final int __AID_ISSET_ID = 4;
  private static final int __TORID_ISSET_ID = 5;
  private static final int __FRRID_ISSET_ID = 6;
  private static final int __SUB_ISSET_ID = 7;
  private static final int __TIME_ISSET_ID = 8;
  private static final int __INDEX_ISSET_ID = 9;
  private static final int __GAID_ISSET_ID = 10;
  private short __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields._ID,_Fields.TYPE,_Fields.FR_UID,_Fields.TO_UID,_Fields.RID,_Fields.AID,_Fields.TO_RID,_Fields.FR_RID,_Fields.SUB,_Fields.NAME,_Fields.CONTENT,_Fields.TIME,_Fields.INDEX,_Fields.GA_ID};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields._ID, new org.apache.thrift.meta_data.FieldMetaData("_id", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TYPE, new org.apache.thrift.meta_data.FieldMetaData("type", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.FR_UID, new org.apache.thrift.meta_data.FieldMetaData("frUid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TO_UID, new org.apache.thrift.meta_data.FieldMetaData("toUid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.RID, new org.apache.thrift.meta_data.FieldMetaData("rid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.AID, new org.apache.thrift.meta_data.FieldMetaData("aid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TO_RID, new org.apache.thrift.meta_data.FieldMetaData("toRid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.FR_RID, new org.apache.thrift.meta_data.FieldMetaData("frRid", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SUB, new org.apache.thrift.meta_data.FieldMetaData("sub", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.CONTENT, new org.apache.thrift.meta_data.FieldMetaData("content", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.TIME, new org.apache.thrift.meta_data.FieldMetaData("time", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.INDEX, new org.apache.thrift.meta_data.FieldMetaData("index", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.GA_ID, new org.apache.thrift.meta_data.FieldMetaData("gaId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Msg.class, metaDataMap);
  }

  public Msg() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Msg(Msg other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSet_id()) {
      this._id = other._id;
    }
    this.type = other.type;
    this.frUid = other.frUid;
    this.toUid = other.toUid;
    this.rid = other.rid;
    this.aid = other.aid;
    this.toRid = other.toRid;
    this.frRid = other.frRid;
    this.sub = other.sub;
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetContent()) {
      this.content = other.content;
    }
    this.time = other.time;
    this.index = other.index;
    this.gaId = other.gaId;
  }

  public Msg deepCopy() {
    return new Msg(this);
  }

  @Override
  public void clear() {
    this._id = null;
    setTypeIsSet(false);
    this.type = 0;
    setFrUidIsSet(false);
    this.frUid = 0;
    setToUidIsSet(false);
    this.toUid = 0;
    setRidIsSet(false);
    this.rid = 0;
    setAidIsSet(false);
    this.aid = 0;
    setToRidIsSet(false);
    this.toRid = 0;
    setFrRidIsSet(false);
    this.frRid = 0;
    setSubIsSet(false);
    this.sub = 0;
    this.name = null;
    this.content = null;
    setTimeIsSet(false);
    this.time = 0;
    setIndexIsSet(false);
    this.index = 0;
    setGaIdIsSet(false);
    this.gaId = 0;
  }

  public String get_id() {
    return this._id;
  }

  public Msg set_id(String _id) {
    this._id = _id;
    return this;
  }

  public void unset_id() {
    this._id = null;
  }

  /** Returns true if field _id is set (has been assigned a value) and false otherwise */
  public boolean isSet_id() {
    return this._id != null;
  }

  public void set_idIsSet(boolean value) {
    if (!value) {
      this._id = null;
    }
  }

  public int getType() {
    return this.type;
  }

  public Msg setType(int type) {
    this.type = type;
    setTypeIsSet(true);
    return this;
  }

  public void unsetType() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  /** Returns true if field type is set (has been assigned a value) and false otherwise */
  public boolean isSetType() {
    return EncodingUtils.testBit(__isset_bitfield, __TYPE_ISSET_ID);
  }

  public void setTypeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TYPE_ISSET_ID, value);
  }

  public long getFrUid() {
    return this.frUid;
  }

  public Msg setFrUid(long frUid) {
    this.frUid = frUid;
    setFrUidIsSet(true);
    return this;
  }

  public void unsetFrUid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FRUID_ISSET_ID);
  }

  /** Returns true if field frUid is set (has been assigned a value) and false otherwise */
  public boolean isSetFrUid() {
    return EncodingUtils.testBit(__isset_bitfield, __FRUID_ISSET_ID);
  }

  public void setFrUidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FRUID_ISSET_ID, value);
  }

  public long getToUid() {
    return this.toUid;
  }

  public Msg setToUid(long toUid) {
    this.toUid = toUid;
    setToUidIsSet(true);
    return this;
  }

  public void unsetToUid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TOUID_ISSET_ID);
  }

  /** Returns true if field toUid is set (has been assigned a value) and false otherwise */
  public boolean isSetToUid() {
    return EncodingUtils.testBit(__isset_bitfield, __TOUID_ISSET_ID);
  }

  public void setToUidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TOUID_ISSET_ID, value);
  }

  public long getRid() {
    return this.rid;
  }

  public Msg setRid(long rid) {
    this.rid = rid;
    setRidIsSet(true);
    return this;
  }

  public void unsetRid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __RID_ISSET_ID);
  }

  /** Returns true if field rid is set (has been assigned a value) and false otherwise */
  public boolean isSetRid() {
    return EncodingUtils.testBit(__isset_bitfield, __RID_ISSET_ID);
  }

  public void setRidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __RID_ISSET_ID, value);
  }

  public long getAid() {
    return this.aid;
  }

  public Msg setAid(long aid) {
    this.aid = aid;
    setAidIsSet(true);
    return this;
  }

  public void unsetAid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __AID_ISSET_ID);
  }

  /** Returns true if field aid is set (has been assigned a value) and false otherwise */
  public boolean isSetAid() {
    return EncodingUtils.testBit(__isset_bitfield, __AID_ISSET_ID);
  }

  public void setAidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __AID_ISSET_ID, value);
  }

  public long getToRid() {
    return this.toRid;
  }

  public Msg setToRid(long toRid) {
    this.toRid = toRid;
    setToRidIsSet(true);
    return this;
  }

  public void unsetToRid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TORID_ISSET_ID);
  }

  /** Returns true if field toRid is set (has been assigned a value) and false otherwise */
  public boolean isSetToRid() {
    return EncodingUtils.testBit(__isset_bitfield, __TORID_ISSET_ID);
  }

  public void setToRidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TORID_ISSET_ID, value);
  }

  public long getFrRid() {
    return this.frRid;
  }

  public Msg setFrRid(long frRid) {
    this.frRid = frRid;
    setFrRidIsSet(true);
    return this;
  }

  public void unsetFrRid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __FRRID_ISSET_ID);
  }

  /** Returns true if field frRid is set (has been assigned a value) and false otherwise */
  public boolean isSetFrRid() {
    return EncodingUtils.testBit(__isset_bitfield, __FRRID_ISSET_ID);
  }

  public void setFrRidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __FRRID_ISSET_ID, value);
  }

  public int getSub() {
    return this.sub;
  }

  public Msg setSub(int sub) {
    this.sub = sub;
    setSubIsSet(true);
    return this;
  }

  public void unsetSub() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SUB_ISSET_ID);
  }

  /** Returns true if field sub is set (has been assigned a value) and false otherwise */
  public boolean isSetSub() {
    return EncodingUtils.testBit(__isset_bitfield, __SUB_ISSET_ID);
  }

  public void setSubIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SUB_ISSET_ID, value);
  }

  public String getName() {
    return this.name;
  }

  public Msg setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public String getContent() {
    return this.content;
  }

  public Msg setContent(String content) {
    this.content = content;
    return this;
  }

  public void unsetContent() {
    this.content = null;
  }

  /** Returns true if field content is set (has been assigned a value) and false otherwise */
  public boolean isSetContent() {
    return this.content != null;
  }

  public void setContentIsSet(boolean value) {
    if (!value) {
      this.content = null;
    }
  }

  public long getTime() {
    return this.time;
  }

  public Msg setTime(long time) {
    this.time = time;
    setTimeIsSet(true);
    return this;
  }

  public void unsetTime() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TIME_ISSET_ID);
  }

  /** Returns true if field time is set (has been assigned a value) and false otherwise */
  public boolean isSetTime() {
    return EncodingUtils.testBit(__isset_bitfield, __TIME_ISSET_ID);
  }

  public void setTimeIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TIME_ISSET_ID, value);
  }

  public int getIndex() {
    return this.index;
  }

  public Msg setIndex(int index) {
    this.index = index;
    setIndexIsSet(true);
    return this;
  }

  public void unsetIndex() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __INDEX_ISSET_ID);
  }

  /** Returns true if field index is set (has been assigned a value) and false otherwise */
  public boolean isSetIndex() {
    return EncodingUtils.testBit(__isset_bitfield, __INDEX_ISSET_ID);
  }

  public void setIndexIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __INDEX_ISSET_ID, value);
  }

  public long getGaId() {
    return this.gaId;
  }

  public Msg setGaId(long gaId) {
    this.gaId = gaId;
    setGaIdIsSet(true);
    return this;
  }

  public void unsetGaId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __GAID_ISSET_ID);
  }

  /** Returns true if field gaId is set (has been assigned a value) and false otherwise */
  public boolean isSetGaId() {
    return EncodingUtils.testBit(__isset_bitfield, __GAID_ISSET_ID);
  }

  public void setGaIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __GAID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case _ID:
      if (value == null) {
        unset_id();
      } else {
        set_id((String)value);
      }
      break;

    case TYPE:
      if (value == null) {
        unsetType();
      } else {
        setType((Integer)value);
      }
      break;

    case FR_UID:
      if (value == null) {
        unsetFrUid();
      } else {
        setFrUid((Long)value);
      }
      break;

    case TO_UID:
      if (value == null) {
        unsetToUid();
      } else {
        setToUid((Long)value);
      }
      break;

    case RID:
      if (value == null) {
        unsetRid();
      } else {
        setRid((Long)value);
      }
      break;

    case AID:
      if (value == null) {
        unsetAid();
      } else {
        setAid((Long)value);
      }
      break;

    case TO_RID:
      if (value == null) {
        unsetToRid();
      } else {
        setToRid((Long)value);
      }
      break;

    case FR_RID:
      if (value == null) {
        unsetFrRid();
      } else {
        setFrRid((Long)value);
      }
      break;

    case SUB:
      if (value == null) {
        unsetSub();
      } else {
        setSub((Integer)value);
      }
      break;

    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case CONTENT:
      if (value == null) {
        unsetContent();
      } else {
        setContent((String)value);
      }
      break;

    case TIME:
      if (value == null) {
        unsetTime();
      } else {
        setTime((Long)value);
      }
      break;

    case INDEX:
      if (value == null) {
        unsetIndex();
      } else {
        setIndex((Integer)value);
      }
      break;

    case GA_ID:
      if (value == null) {
        unsetGaId();
      } else {
        setGaId((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case _ID:
      return get_id();

    case TYPE:
      return getType();

    case FR_UID:
      return getFrUid();

    case TO_UID:
      return getToUid();

    case RID:
      return getRid();

    case AID:
      return getAid();

    case TO_RID:
      return getToRid();

    case FR_RID:
      return getFrRid();

    case SUB:
      return getSub();

    case NAME:
      return getName();

    case CONTENT:
      return getContent();

    case TIME:
      return getTime();

    case INDEX:
      return getIndex();

    case GA_ID:
      return getGaId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case _ID:
      return isSet_id();
    case TYPE:
      return isSetType();
    case FR_UID:
      return isSetFrUid();
    case TO_UID:
      return isSetToUid();
    case RID:
      return isSetRid();
    case AID:
      return isSetAid();
    case TO_RID:
      return isSetToRid();
    case FR_RID:
      return isSetFrRid();
    case SUB:
      return isSetSub();
    case NAME:
      return isSetName();
    case CONTENT:
      return isSetContent();
    case TIME:
      return isSetTime();
    case INDEX:
      return isSetIndex();
    case GA_ID:
      return isSetGaId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Msg)
      return this.equals((Msg)that);
    return false;
  }

  public boolean equals(Msg that) {
    if (that == null)
      return false;

    boolean this_present__id = true && this.isSet_id();
    boolean that_present__id = true && that.isSet_id();
    if (this_present__id || that_present__id) {
      if (!(this_present__id && that_present__id))
        return false;
      if (!this._id.equals(that._id))
        return false;
    }

    boolean this_present_type = true && this.isSetType();
    boolean that_present_type = true && that.isSetType();
    if (this_present_type || that_present_type) {
      if (!(this_present_type && that_present_type))
        return false;
      if (this.type != that.type)
        return false;
    }

    boolean this_present_frUid = true && this.isSetFrUid();
    boolean that_present_frUid = true && that.isSetFrUid();
    if (this_present_frUid || that_present_frUid) {
      if (!(this_present_frUid && that_present_frUid))
        return false;
      if (this.frUid != that.frUid)
        return false;
    }

    boolean this_present_toUid = true && this.isSetToUid();
    boolean that_present_toUid = true && that.isSetToUid();
    if (this_present_toUid || that_present_toUid) {
      if (!(this_present_toUid && that_present_toUid))
        return false;
      if (this.toUid != that.toUid)
        return false;
    }

    boolean this_present_rid = true && this.isSetRid();
    boolean that_present_rid = true && that.isSetRid();
    if (this_present_rid || that_present_rid) {
      if (!(this_present_rid && that_present_rid))
        return false;
      if (this.rid != that.rid)
        return false;
    }

    boolean this_present_aid = true && this.isSetAid();
    boolean that_present_aid = true && that.isSetAid();
    if (this_present_aid || that_present_aid) {
      if (!(this_present_aid && that_present_aid))
        return false;
      if (this.aid != that.aid)
        return false;
    }

    boolean this_present_toRid = true && this.isSetToRid();
    boolean that_present_toRid = true && that.isSetToRid();
    if (this_present_toRid || that_present_toRid) {
      if (!(this_present_toRid && that_present_toRid))
        return false;
      if (this.toRid != that.toRid)
        return false;
    }

    boolean this_present_frRid = true && this.isSetFrRid();
    boolean that_present_frRid = true && that.isSetFrRid();
    if (this_present_frRid || that_present_frRid) {
      if (!(this_present_frRid && that_present_frRid))
        return false;
      if (this.frRid != that.frRid)
        return false;
    }

    boolean this_present_sub = true && this.isSetSub();
    boolean that_present_sub = true && that.isSetSub();
    if (this_present_sub || that_present_sub) {
      if (!(this_present_sub && that_present_sub))
        return false;
      if (this.sub != that.sub)
        return false;
    }

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_content = true && this.isSetContent();
    boolean that_present_content = true && that.isSetContent();
    if (this_present_content || that_present_content) {
      if (!(this_present_content && that_present_content))
        return false;
      if (!this.content.equals(that.content))
        return false;
    }

    boolean this_present_time = true && this.isSetTime();
    boolean that_present_time = true && that.isSetTime();
    if (this_present_time || that_present_time) {
      if (!(this_present_time && that_present_time))
        return false;
      if (this.time != that.time)
        return false;
    }

    boolean this_present_index = true && this.isSetIndex();
    boolean that_present_index = true && that.isSetIndex();
    if (this_present_index || that_present_index) {
      if (!(this_present_index && that_present_index))
        return false;
      if (this.index != that.index)
        return false;
    }

    boolean this_present_gaId = true && this.isSetGaId();
    boolean that_present_gaId = true && that.isSetGaId();
    if (this_present_gaId || that_present_gaId) {
      if (!(this_present_gaId && that_present_gaId))
        return false;
      if (this.gaId != that.gaId)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present__id = true && (isSet_id());
    list.add(present__id);
    if (present__id)
      list.add(_id);

    boolean present_type = true && (isSetType());
    list.add(present_type);
    if (present_type)
      list.add(type);

    boolean present_frUid = true && (isSetFrUid());
    list.add(present_frUid);
    if (present_frUid)
      list.add(frUid);

    boolean present_toUid = true && (isSetToUid());
    list.add(present_toUid);
    if (present_toUid)
      list.add(toUid);

    boolean present_rid = true && (isSetRid());
    list.add(present_rid);
    if (present_rid)
      list.add(rid);

    boolean present_aid = true && (isSetAid());
    list.add(present_aid);
    if (present_aid)
      list.add(aid);

    boolean present_toRid = true && (isSetToRid());
    list.add(present_toRid);
    if (present_toRid)
      list.add(toRid);

    boolean present_frRid = true && (isSetFrRid());
    list.add(present_frRid);
    if (present_frRid)
      list.add(frRid);

    boolean present_sub = true && (isSetSub());
    list.add(present_sub);
    if (present_sub)
      list.add(sub);

    boolean present_name = true && (isSetName());
    list.add(present_name);
    if (present_name)
      list.add(name);

    boolean present_content = true && (isSetContent());
    list.add(present_content);
    if (present_content)
      list.add(content);

    boolean present_time = true && (isSetTime());
    list.add(present_time);
    if (present_time)
      list.add(time);

    boolean present_index = true && (isSetIndex());
    list.add(present_index);
    if (present_index)
      list.add(index);

    boolean present_gaId = true && (isSetGaId());
    list.add(present_gaId);
    if (present_gaId)
      list.add(gaId);

    return list.hashCode();
  }

  @Override
  public int compareTo(Msg other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSet_id()).compareTo(other.isSet_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSet_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this._id, other._id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetType()).compareTo(other.isSetType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.type, other.type);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFrUid()).compareTo(other.isSetFrUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFrUid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.frUid, other.frUid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetToUid()).compareTo(other.isSetToUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetToUid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.toUid, other.toUid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetRid()).compareTo(other.isSetRid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rid, other.rid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAid()).compareTo(other.isSetAid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.aid, other.aid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetToRid()).compareTo(other.isSetToRid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetToRid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.toRid, other.toRid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetFrRid()).compareTo(other.isSetFrRid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFrRid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.frRid, other.frRid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetSub()).compareTo(other.isSetSub());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSub()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sub, other.sub);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetContent()).compareTo(other.isSetContent());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetContent()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.content, other.content);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTime()).compareTo(other.isSetTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.time, other.time);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetIndex()).compareTo(other.isSetIndex());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIndex()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.index, other.index);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetGaId()).compareTo(other.isSetGaId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGaId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gaId, other.gaId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Msg(");
    boolean first = true;

    if (isSet_id()) {
      sb.append("_id:");
      if (this._id == null) {
        sb.append("null");
      } else {
        sb.append(this._id);
      }
      first = false;
    }
    if (isSetType()) {
      if (!first) sb.append(", ");
      sb.append("type:");
      sb.append(this.type);
      first = false;
    }
    if (isSetFrUid()) {
      if (!first) sb.append(", ");
      sb.append("frUid:");
      sb.append(this.frUid);
      first = false;
    }
    if (isSetToUid()) {
      if (!first) sb.append(", ");
      sb.append("toUid:");
      sb.append(this.toUid);
      first = false;
    }
    if (isSetRid()) {
      if (!first) sb.append(", ");
      sb.append("rid:");
      sb.append(this.rid);
      first = false;
    }
    if (isSetAid()) {
      if (!first) sb.append(", ");
      sb.append("aid:");
      sb.append(this.aid);
      first = false;
    }
    if (isSetToRid()) {
      if (!first) sb.append(", ");
      sb.append("toRid:");
      sb.append(this.toRid);
      first = false;
    }
    if (isSetFrRid()) {
      if (!first) sb.append(", ");
      sb.append("frRid:");
      sb.append(this.frRid);
      first = false;
    }
    if (isSetSub()) {
      if (!first) sb.append(", ");
      sb.append("sub:");
      sb.append(this.sub);
      first = false;
    }
    if (isSetName()) {
      if (!first) sb.append(", ");
      sb.append("name:");
      if (this.name == null) {
        sb.append("null");
      } else {
        sb.append(this.name);
      }
      first = false;
    }
    if (isSetContent()) {
      if (!first) sb.append(", ");
      sb.append("content:");
      if (this.content == null) {
        sb.append("null");
      } else {
        sb.append(this.content);
      }
      first = false;
    }
    if (isSetTime()) {
      if (!first) sb.append(", ");
      sb.append("time:");
      sb.append(this.time);
      first = false;
    }
    if (isSetIndex()) {
      if (!first) sb.append(", ");
      sb.append("index:");
      sb.append(this.index);
      first = false;
    }
    if (isSetGaId()) {
      if (!first) sb.append(", ");
      sb.append("gaId:");
      sb.append(this.gaId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MsgStandardSchemeFactory implements SchemeFactory {
    public MsgStandardScheme getScheme() {
      return new MsgStandardScheme();
    }
  }

  private static class MsgStandardScheme extends StandardScheme<Msg> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Msg struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // _ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct._id = iprot.readString();
              struct.set_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.type = iprot.readI32();
              struct.setTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // FR_UID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.frUid = iprot.readI64();
              struct.setFrUidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // TO_UID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.toUid = iprot.readI64();
              struct.setToUidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // RID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.rid = iprot.readI64();
              struct.setRidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // AID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.aid = iprot.readI64();
              struct.setAidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // TO_RID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.toRid = iprot.readI64();
              struct.setToRidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // FR_RID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.frRid = iprot.readI64();
              struct.setFrRidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // SUB
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.sub = iprot.readI32();
              struct.setSubIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // CONTENT
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.content = iprot.readString();
              struct.setContentIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.time = iprot.readI64();
              struct.setTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // INDEX
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.index = iprot.readI32();
              struct.setIndexIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // GA_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.gaId = iprot.readI64();
              struct.setGaIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Msg struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct._id != null) {
        if (struct.isSet_id()) {
          oprot.writeFieldBegin(_ID_FIELD_DESC);
          oprot.writeString(struct._id);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetType()) {
        oprot.writeFieldBegin(TYPE_FIELD_DESC);
        oprot.writeI32(struct.type);
        oprot.writeFieldEnd();
      }
      if (struct.isSetFrUid()) {
        oprot.writeFieldBegin(FR_UID_FIELD_DESC);
        oprot.writeI64(struct.frUid);
        oprot.writeFieldEnd();
      }
      if (struct.isSetToUid()) {
        oprot.writeFieldBegin(TO_UID_FIELD_DESC);
        oprot.writeI64(struct.toUid);
        oprot.writeFieldEnd();
      }
      if (struct.isSetRid()) {
        oprot.writeFieldBegin(RID_FIELD_DESC);
        oprot.writeI64(struct.rid);
        oprot.writeFieldEnd();
      }
      if (struct.isSetAid()) {
        oprot.writeFieldBegin(AID_FIELD_DESC);
        oprot.writeI64(struct.aid);
        oprot.writeFieldEnd();
      }
      if (struct.isSetToRid()) {
        oprot.writeFieldBegin(TO_RID_FIELD_DESC);
        oprot.writeI64(struct.toRid);
        oprot.writeFieldEnd();
      }
      if (struct.isSetFrRid()) {
        oprot.writeFieldBegin(FR_RID_FIELD_DESC);
        oprot.writeI64(struct.frRid);
        oprot.writeFieldEnd();
      }
      if (struct.isSetSub()) {
        oprot.writeFieldBegin(SUB_FIELD_DESC);
        oprot.writeI32(struct.sub);
        oprot.writeFieldEnd();
      }
      if (struct.name != null) {
        if (struct.isSetName()) {
          oprot.writeFieldBegin(NAME_FIELD_DESC);
          oprot.writeString(struct.name);
          oprot.writeFieldEnd();
        }
      }
      if (struct.content != null) {
        if (struct.isSetContent()) {
          oprot.writeFieldBegin(CONTENT_FIELD_DESC);
          oprot.writeString(struct.content);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetTime()) {
        oprot.writeFieldBegin(TIME_FIELD_DESC);
        oprot.writeI64(struct.time);
        oprot.writeFieldEnd();
      }
      if (struct.isSetIndex()) {
        oprot.writeFieldBegin(INDEX_FIELD_DESC);
        oprot.writeI32(struct.index);
        oprot.writeFieldEnd();
      }
      if (struct.isSetGaId()) {
        oprot.writeFieldBegin(GA_ID_FIELD_DESC);
        oprot.writeI64(struct.gaId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MsgTupleSchemeFactory implements SchemeFactory {
    public MsgTupleScheme getScheme() {
      return new MsgTupleScheme();
    }
  }

  private static class MsgTupleScheme extends TupleScheme<Msg> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Msg struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSet_id()) {
        optionals.set(0);
      }
      if (struct.isSetType()) {
        optionals.set(1);
      }
      if (struct.isSetFrUid()) {
        optionals.set(2);
      }
      if (struct.isSetToUid()) {
        optionals.set(3);
      }
      if (struct.isSetRid()) {
        optionals.set(4);
      }
      if (struct.isSetAid()) {
        optionals.set(5);
      }
      if (struct.isSetToRid()) {
        optionals.set(6);
      }
      if (struct.isSetFrRid()) {
        optionals.set(7);
      }
      if (struct.isSetSub()) {
        optionals.set(8);
      }
      if (struct.isSetName()) {
        optionals.set(9);
      }
      if (struct.isSetContent()) {
        optionals.set(10);
      }
      if (struct.isSetTime()) {
        optionals.set(11);
      }
      if (struct.isSetIndex()) {
        optionals.set(12);
      }
      if (struct.isSetGaId()) {
        optionals.set(13);
      }
      oprot.writeBitSet(optionals, 14);
      if (struct.isSet_id()) {
        oprot.writeString(struct._id);
      }
      if (struct.isSetType()) {
        oprot.writeI32(struct.type);
      }
      if (struct.isSetFrUid()) {
        oprot.writeI64(struct.frUid);
      }
      if (struct.isSetToUid()) {
        oprot.writeI64(struct.toUid);
      }
      if (struct.isSetRid()) {
        oprot.writeI64(struct.rid);
      }
      if (struct.isSetAid()) {
        oprot.writeI64(struct.aid);
      }
      if (struct.isSetToRid()) {
        oprot.writeI64(struct.toRid);
      }
      if (struct.isSetFrRid()) {
        oprot.writeI64(struct.frRid);
      }
      if (struct.isSetSub()) {
        oprot.writeI32(struct.sub);
      }
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetContent()) {
        oprot.writeString(struct.content);
      }
      if (struct.isSetTime()) {
        oprot.writeI64(struct.time);
      }
      if (struct.isSetIndex()) {
        oprot.writeI32(struct.index);
      }
      if (struct.isSetGaId()) {
        oprot.writeI64(struct.gaId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Msg struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(14);
      if (incoming.get(0)) {
        struct._id = iprot.readString();
        struct.set_idIsSet(true);
      }
      if (incoming.get(1)) {
        struct.type = iprot.readI32();
        struct.setTypeIsSet(true);
      }
      if (incoming.get(2)) {
        struct.frUid = iprot.readI64();
        struct.setFrUidIsSet(true);
      }
      if (incoming.get(3)) {
        struct.toUid = iprot.readI64();
        struct.setToUidIsSet(true);
      }
      if (incoming.get(4)) {
        struct.rid = iprot.readI64();
        struct.setRidIsSet(true);
      }
      if (incoming.get(5)) {
        struct.aid = iprot.readI64();
        struct.setAidIsSet(true);
      }
      if (incoming.get(6)) {
        struct.toRid = iprot.readI64();
        struct.setToRidIsSet(true);
      }
      if (incoming.get(7)) {
        struct.frRid = iprot.readI64();
        struct.setFrRidIsSet(true);
      }
      if (incoming.get(8)) {
        struct.sub = iprot.readI32();
        struct.setSubIsSet(true);
      }
      if (incoming.get(9)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(10)) {
        struct.content = iprot.readString();
        struct.setContentIsSet(true);
      }
      if (incoming.get(11)) {
        struct.time = iprot.readI64();
        struct.setTimeIsSet(true);
      }
      if (incoming.get(12)) {
        struct.index = iprot.readI32();
        struct.setIndexIsSet(true);
      }
      if (incoming.get(13)) {
        struct.gaId = iprot.readI64();
        struct.setGaIdIsSet(true);
      }
    }
  }

}

