// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package cn.superid.webapp.notice.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NoticeMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.superid.webapp.notice.proto.NoticeMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>optional string subType = 2;</code>
     */
    boolean hasSubType();
    /**
     * <code>optional string subType = 2;</code>
     */
    java.lang.String getSubType();
    /**
     * <code>optional string subType = 2;</code>
     */
    com.google.protobuf.ByteString
        getSubTypeBytes();

    /**
     * <code>optional string displayName = 3;</code>
     */
    boolean hasDisplayName();
    /**
     * <code>optional string displayName = 3;</code>
     */
    java.lang.String getDisplayName();
    /**
     * <code>optional string displayName = 3;</code>
     */
    com.google.protobuf.ByteString
        getDisplayNameBytes();

    /**
     * <code>optional uint64 fromUserId = 4;</code>
     */
    boolean hasFromUserId();
    /**
     * <code>optional uint64 fromUserId = 4;</code>
     */
    long getFromUserId();

    /**
     * <code>optional uint64 toUserId = 5;</code>
     */
    boolean hasToUserId();
    /**
     * <code>optional uint64 toUserId = 5;</code>
     */
    long getToUserId();

    /**
     * <code>optional uint64 toRoleId = 6;</code>
     */
    boolean hasToRoleId();
    /**
     * <code>optional uint64 toRoleId = 6;</code>
     */
    long getToRoleId();

    /**
     * <code>optional uint64 affairId = 7;</code>
     */
    boolean hasAffairId();
    /**
     * <code>optional uint64 affairId = 7;</code>
     */
    long getAffairId();

    /**
     * <code>optional uint64 relatedId = 8;</code>
     */
    boolean hasRelatedId();
    /**
     * <code>optional uint64 relatedId = 8;</code>
     */
    long getRelatedId();

    /**
     * <code>optional uint32 state = 9;</code>
     */
    boolean hasState();
    /**
     * <code>optional uint32 state = 9;</code>
     */
    int getState();

    /**
     * <code>optional string content = 10;</code>
     */
    boolean hasContent();
    /**
     * <code>optional string content = 10;</code>
     */
    java.lang.String getContent();
    /**
     * <code>optional string content = 10;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code cn.superid.webapp.notice.proto.NoticeMsg}
   */
  public  static final class NoticeMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.superid.webapp.notice.proto.NoticeMsg)
      NoticeMsgOrBuilder {
    // Use NoticeMsg.newBuilder() to construct.
    private NoticeMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NoticeMsg() {
      type_ = "";
      subType_ = "";
      displayName_ = "";
      fromUserId_ = 0L;
      toUserId_ = 0L;
      toRoleId_ = 0L;
      affairId_ = 0L;
      relatedId_ = 0L;
      state_ = 0;
      content_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private NoticeMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              type_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              subType_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              displayName_ = bs;
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              fromUserId_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              toUserId_ = input.readUInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              toRoleId_ = input.readUInt64();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              affairId_ = input.readUInt64();
              break;
            }
            case 64: {
              bitField0_ |= 0x00000080;
              relatedId_ = input.readUInt64();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              state_ = input.readUInt32();
              break;
            }
            case 82: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000200;
              content_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_NoticeMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_NoticeMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.superid.webapp.notice.proto.Message.NoticeMsg.class, cn.superid.webapp.notice.proto.Message.NoticeMsg.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUBTYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object subType_;
    /**
     * <code>optional string subType = 2;</code>
     */
    public boolean hasSubType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string subType = 2;</code>
     */
    public java.lang.String getSubType() {
      java.lang.Object ref = subType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          subType_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string subType = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSubTypeBytes() {
      java.lang.Object ref = subType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        subType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPLAYNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object displayName_;
    /**
     * <code>optional string displayName = 3;</code>
     */
    public boolean hasDisplayName() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string displayName = 3;</code>
     */
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          displayName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string displayName = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FROMUSERID_FIELD_NUMBER = 4;
    private long fromUserId_;
    /**
     * <code>optional uint64 fromUserId = 4;</code>
     */
    public boolean hasFromUserId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 fromUserId = 4;</code>
     */
    public long getFromUserId() {
      return fromUserId_;
    }

    public static final int TOUSERID_FIELD_NUMBER = 5;
    private long toUserId_;
    /**
     * <code>optional uint64 toUserId = 5;</code>
     */
    public boolean hasToUserId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 toUserId = 5;</code>
     */
    public long getToUserId() {
      return toUserId_;
    }

    public static final int TOROLEID_FIELD_NUMBER = 6;
    private long toRoleId_;
    /**
     * <code>optional uint64 toRoleId = 6;</code>
     */
    public boolean hasToRoleId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional uint64 toRoleId = 6;</code>
     */
    public long getToRoleId() {
      return toRoleId_;
    }

    public static final int AFFAIRID_FIELD_NUMBER = 7;
    private long affairId_;
    /**
     * <code>optional uint64 affairId = 7;</code>
     */
    public boolean hasAffairId() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint64 affairId = 7;</code>
     */
    public long getAffairId() {
      return affairId_;
    }

    public static final int RELATEDID_FIELD_NUMBER = 8;
    private long relatedId_;
    /**
     * <code>optional uint64 relatedId = 8;</code>
     */
    public boolean hasRelatedId() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional uint64 relatedId = 8;</code>
     */
    public long getRelatedId() {
      return relatedId_;
    }

    public static final int STATE_FIELD_NUMBER = 9;
    private int state_;
    /**
     * <code>optional uint32 state = 9;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional uint32 state = 9;</code>
     */
    public int getState() {
      return state_;
    }

    public static final int CONTENT_FIELD_NUMBER = 10;
    private volatile java.lang.Object content_;
    /**
     * <code>optional string content = 10;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional string content = 10;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string content = 10;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, subType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, displayName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, fromUserId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, toUserId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt64(6, toRoleId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt64(7, affairId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeUInt64(8, relatedId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, state_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, content_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, subType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, displayName_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, fromUserId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, toUserId_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, toRoleId_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, affairId_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, relatedId_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, state_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, content_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.superid.webapp.notice.proto.Message.NoticeMsg)) {
        return super.equals(obj);
      }
      cn.superid.webapp.notice.proto.Message.NoticeMsg other = (cn.superid.webapp.notice.proto.Message.NoticeMsg) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      result = result && (hasSubType() == other.hasSubType());
      if (hasSubType()) {
        result = result && getSubType()
            .equals(other.getSubType());
      }
      result = result && (hasDisplayName() == other.hasDisplayName());
      if (hasDisplayName()) {
        result = result && getDisplayName()
            .equals(other.getDisplayName());
      }
      result = result && (hasFromUserId() == other.hasFromUserId());
      if (hasFromUserId()) {
        result = result && (getFromUserId()
            == other.getFromUserId());
      }
      result = result && (hasToUserId() == other.hasToUserId());
      if (hasToUserId()) {
        result = result && (getToUserId()
            == other.getToUserId());
      }
      result = result && (hasToRoleId() == other.hasToRoleId());
      if (hasToRoleId()) {
        result = result && (getToRoleId()
            == other.getToRoleId());
      }
      result = result && (hasAffairId() == other.hasAffairId());
      if (hasAffairId()) {
        result = result && (getAffairId()
            == other.getAffairId());
      }
      result = result && (hasRelatedId() == other.hasRelatedId());
      if (hasRelatedId()) {
        result = result && (getRelatedId()
            == other.getRelatedId());
      }
      result = result && (hasState() == other.hasState());
      if (hasState()) {
        result = result && (getState()
            == other.getState());
      }
      result = result && (hasContent() == other.hasContent());
      if (hasContent()) {
        result = result && getContent()
            .equals(other.getContent());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasSubType()) {
        hash = (37 * hash) + SUBTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getSubType().hashCode();
      }
      if (hasDisplayName()) {
        hash = (37 * hash) + DISPLAYNAME_FIELD_NUMBER;
        hash = (53 * hash) + getDisplayName().hashCode();
      }
      if (hasFromUserId()) {
        hash = (37 * hash) + FROMUSERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getFromUserId());
      }
      if (hasToUserId()) {
        hash = (37 * hash) + TOUSERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getToUserId());
      }
      if (hasToRoleId()) {
        hash = (37 * hash) + TOROLEID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getToRoleId());
      }
      if (hasAffairId()) {
        hash = (37 * hash) + AFFAIRID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAffairId());
      }
      if (hasRelatedId()) {
        hash = (37 * hash) + RELATEDID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getRelatedId());
      }
      if (hasState()) {
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState();
      }
      if (hasContent()) {
        hash = (37 * hash) + CONTENT_FIELD_NUMBER;
        hash = (53 * hash) + getContent().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.superid.webapp.notice.proto.Message.NoticeMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.superid.webapp.notice.proto.Message.NoticeMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.superid.webapp.notice.proto.NoticeMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.superid.webapp.notice.proto.NoticeMsg)
        cn.superid.webapp.notice.proto.Message.NoticeMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_NoticeMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_NoticeMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.superid.webapp.notice.proto.Message.NoticeMsg.class, cn.superid.webapp.notice.proto.Message.NoticeMsg.Builder.class);
      }

      // Construct using cn.superid.webapp.notice.proto.Message.NoticeMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        subType_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        displayName_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        fromUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        toUserId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        toRoleId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        affairId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000040);
        relatedId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_NoticeMsg_descriptor;
      }

      public cn.superid.webapp.notice.proto.Message.NoticeMsg getDefaultInstanceForType() {
        return cn.superid.webapp.notice.proto.Message.NoticeMsg.getDefaultInstance();
      }

      public cn.superid.webapp.notice.proto.Message.NoticeMsg build() {
        cn.superid.webapp.notice.proto.Message.NoticeMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.superid.webapp.notice.proto.Message.NoticeMsg buildPartial() {
        cn.superid.webapp.notice.proto.Message.NoticeMsg result = new cn.superid.webapp.notice.proto.Message.NoticeMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.subType_ = subType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.displayName_ = displayName_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.fromUserId_ = fromUserId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.toUserId_ = toUserId_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.toRoleId_ = toRoleId_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.affairId_ = affairId_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.relatedId_ = relatedId_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.superid.webapp.notice.proto.Message.NoticeMsg) {
          return mergeFrom((cn.superid.webapp.notice.proto.Message.NoticeMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.superid.webapp.notice.proto.Message.NoticeMsg other) {
        if (other == cn.superid.webapp.notice.proto.Message.NoticeMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasSubType()) {
          bitField0_ |= 0x00000002;
          subType_ = other.subType_;
          onChanged();
        }
        if (other.hasDisplayName()) {
          bitField0_ |= 0x00000004;
          displayName_ = other.displayName_;
          onChanged();
        }
        if (other.hasFromUserId()) {
          setFromUserId(other.getFromUserId());
        }
        if (other.hasToUserId()) {
          setToUserId(other.getToUserId());
        }
        if (other.hasToRoleId()) {
          setToRoleId(other.getToRoleId());
        }
        if (other.hasAffairId()) {
          setAffairId(other.getAffairId());
        }
        if (other.hasRelatedId()) {
          setRelatedId(other.getRelatedId());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000200;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.superid.webapp.notice.proto.Message.NoticeMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.superid.webapp.notice.proto.Message.NoticeMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object subType_ = "";
      /**
       * <code>optional string subType = 2;</code>
       */
      public boolean hasSubType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string subType = 2;</code>
       */
      public java.lang.String getSubType() {
        java.lang.Object ref = subType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            subType_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string subType = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSubTypeBytes() {
        java.lang.Object ref = subType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          subType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string subType = 2;</code>
       */
      public Builder setSubType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        subType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string subType = 2;</code>
       */
      public Builder clearSubType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        subType_ = getDefaultInstance().getSubType();
        onChanged();
        return this;
      }
      /**
       * <code>optional string subType = 2;</code>
       */
      public Builder setSubTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        subType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object displayName_ = "";
      /**
       * <code>optional string displayName = 3;</code>
       */
      public boolean hasDisplayName() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public java.lang.String getDisplayName() {
        java.lang.Object ref = displayName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            displayName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDisplayNameBytes() {
        java.lang.Object ref = displayName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          displayName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public Builder setDisplayName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        displayName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public Builder clearDisplayName() {
        bitField0_ = (bitField0_ & ~0x00000004);
        displayName_ = getDefaultInstance().getDisplayName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string displayName = 3;</code>
       */
      public Builder setDisplayNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        displayName_ = value;
        onChanged();
        return this;
      }

      private long fromUserId_ ;
      /**
       * <code>optional uint64 fromUserId = 4;</code>
       */
      public boolean hasFromUserId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 fromUserId = 4;</code>
       */
      public long getFromUserId() {
        return fromUserId_;
      }
      /**
       * <code>optional uint64 fromUserId = 4;</code>
       */
      public Builder setFromUserId(long value) {
        bitField0_ |= 0x00000008;
        fromUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 fromUserId = 4;</code>
       */
      public Builder clearFromUserId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        fromUserId_ = 0L;
        onChanged();
        return this;
      }

      private long toUserId_ ;
      /**
       * <code>optional uint64 toUserId = 5;</code>
       */
      public boolean hasToUserId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 toUserId = 5;</code>
       */
      public long getToUserId() {
        return toUserId_;
      }
      /**
       * <code>optional uint64 toUserId = 5;</code>
       */
      public Builder setToUserId(long value) {
        bitField0_ |= 0x00000010;
        toUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 toUserId = 5;</code>
       */
      public Builder clearToUserId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        toUserId_ = 0L;
        onChanged();
        return this;
      }

      private long toRoleId_ ;
      /**
       * <code>optional uint64 toRoleId = 6;</code>
       */
      public boolean hasToRoleId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional uint64 toRoleId = 6;</code>
       */
      public long getToRoleId() {
        return toRoleId_;
      }
      /**
       * <code>optional uint64 toRoleId = 6;</code>
       */
      public Builder setToRoleId(long value) {
        bitField0_ |= 0x00000020;
        toRoleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 toRoleId = 6;</code>
       */
      public Builder clearToRoleId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        toRoleId_ = 0L;
        onChanged();
        return this;
      }

      private long affairId_ ;
      /**
       * <code>optional uint64 affairId = 7;</code>
       */
      public boolean hasAffairId() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint64 affairId = 7;</code>
       */
      public long getAffairId() {
        return affairId_;
      }
      /**
       * <code>optional uint64 affairId = 7;</code>
       */
      public Builder setAffairId(long value) {
        bitField0_ |= 0x00000040;
        affairId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 affairId = 7;</code>
       */
      public Builder clearAffairId() {
        bitField0_ = (bitField0_ & ~0x00000040);
        affairId_ = 0L;
        onChanged();
        return this;
      }

      private long relatedId_ ;
      /**
       * <code>optional uint64 relatedId = 8;</code>
       */
      public boolean hasRelatedId() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional uint64 relatedId = 8;</code>
       */
      public long getRelatedId() {
        return relatedId_;
      }
      /**
       * <code>optional uint64 relatedId = 8;</code>
       */
      public Builder setRelatedId(long value) {
        bitField0_ |= 0x00000080;
        relatedId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 relatedId = 8;</code>
       */
      public Builder clearRelatedId() {
        bitField0_ = (bitField0_ & ~0x00000080);
        relatedId_ = 0L;
        onChanged();
        return this;
      }

      private int state_ ;
      /**
       * <code>optional uint32 state = 9;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional uint32 state = 9;</code>
       */
      public int getState() {
        return state_;
      }
      /**
       * <code>optional uint32 state = 9;</code>
       */
      public Builder setState(int value) {
        bitField0_ |= 0x00000100;
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 state = 9;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000100);
        state_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>optional string content = 10;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string content = 10;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string content = 10;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string content = 10;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 10;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000200);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>optional string content = 10;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
        content_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.superid.webapp.notice.proto.NoticeMsg)
    }

    // @@protoc_insertion_point(class_scope:cn.superid.webapp.notice.proto.NoticeMsg)
    private static final cn.superid.webapp.notice.proto.Message.NoticeMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.superid.webapp.notice.proto.Message.NoticeMsg();
    }

    public static cn.superid.webapp.notice.proto.Message.NoticeMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<NoticeMsg>
        PARSER = new com.google.protobuf.AbstractParser<NoticeMsg>() {
      public NoticeMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new NoticeMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<NoticeMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NoticeMsg> getParserForType() {
      return PARSER;
    }

    public cn.superid.webapp.notice.proto.Message.NoticeMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface EventMsgOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cn.superid.webapp.notice.proto.EventMsg)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>required string type = 1;</code>
     */
    java.lang.String getType();
    /**
     * <code>required string type = 1;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>required uint32 eventType = 2;</code>
     */
    boolean hasEventType();
    /**
     * <code>required uint32 eventType = 2;</code>
     */
    int getEventType();

    /**
     * <code>optional uint64 affairId = 3;</code>
     */
    boolean hasAffairId();
    /**
     * <code>optional uint64 affairId = 3;</code>
     */
    long getAffairId();

    /**
     * <code>optional uint64 groupId = 4;</code>
     */
    boolean hasGroupId();
    /**
     * <code>optional uint64 groupId = 4;</code>
     */
    long getGroupId();

    /**
     * <code>optional uint64 userId = 5;</code>
     */
    boolean hasUserId();
    /**
     * <code>optional uint64 userId = 5;</code>
     */
    long getUserId();
  }
  /**
   * Protobuf type {@code cn.superid.webapp.notice.proto.EventMsg}
   */
  public  static final class EventMsg extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:cn.superid.webapp.notice.proto.EventMsg)
      EventMsgOrBuilder {
    // Use EventMsg.newBuilder() to construct.
    private EventMsg(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventMsg() {
      type_ = "";
      eventType_ = 0;
      affairId_ = 0L;
      groupId_ = 0L;
      userId_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              type_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              eventType_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              affairId_ = input.readUInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              groupId_ = input.readUInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              userId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_EventMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_EventMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cn.superid.webapp.notice.proto.Message.EventMsg.class, cn.superid.webapp.notice.proto.Message.EventMsg.Builder.class);
    }

    private int bitField0_;
    public static final int TYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object type_;
    /**
     * <code>required string type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string type = 1;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          type_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string type = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENTTYPE_FIELD_NUMBER = 2;
    private int eventType_;
    /**
     * <code>required uint32 eventType = 2;</code>
     */
    public boolean hasEventType() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 eventType = 2;</code>
     */
    public int getEventType() {
      return eventType_;
    }

    public static final int AFFAIRID_FIELD_NUMBER = 3;
    private long affairId_;
    /**
     * <code>optional uint64 affairId = 3;</code>
     */
    public boolean hasAffairId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional uint64 affairId = 3;</code>
     */
    public long getAffairId() {
      return affairId_;
    }

    public static final int GROUPID_FIELD_NUMBER = 4;
    private long groupId_;
    /**
     * <code>optional uint64 groupId = 4;</code>
     */
    public boolean hasGroupId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional uint64 groupId = 4;</code>
     */
    public long getGroupId() {
      return groupId_;
    }

    public static final int USERID_FIELD_NUMBER = 5;
    private long userId_;
    /**
     * <code>optional uint64 userId = 5;</code>
     */
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional uint64 userId = 5;</code>
     */
    public long getUserId() {
      return userId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasEventType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, eventType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, affairId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt64(4, groupId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt64(5, userId_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, type_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, eventType_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, affairId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, groupId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, userId_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cn.superid.webapp.notice.proto.Message.EventMsg)) {
        return super.equals(obj);
      }
      cn.superid.webapp.notice.proto.Message.EventMsg other = (cn.superid.webapp.notice.proto.Message.EventMsg) obj;

      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result && getType()
            .equals(other.getType());
      }
      result = result && (hasEventType() == other.hasEventType());
      if (hasEventType()) {
        result = result && (getEventType()
            == other.getEventType());
      }
      result = result && (hasAffairId() == other.hasAffairId());
      if (hasAffairId()) {
        result = result && (getAffairId()
            == other.getAffairId());
      }
      result = result && (hasGroupId() == other.hasGroupId());
      if (hasGroupId()) {
        result = result && (getGroupId()
            == other.getGroupId());
      }
      result = result && (hasUserId() == other.hasUserId());
      if (hasUserId()) {
        result = result && (getUserId()
            == other.getUserId());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
      }
      if (hasEventType()) {
        hash = (37 * hash) + EVENTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getEventType();
      }
      if (hasAffairId()) {
        hash = (37 * hash) + AFFAIRID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getAffairId());
      }
      if (hasGroupId()) {
        hash = (37 * hash) + GROUPID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getGroupId());
      }
      if (hasUserId()) {
        hash = (37 * hash) + USERID_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getUserId());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cn.superid.webapp.notice.proto.Message.EventMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.superid.webapp.notice.proto.Message.EventMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.superid.webapp.notice.proto.Message.EventMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cn.superid.webapp.notice.proto.Message.EventMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cn.superid.webapp.notice.proto.Message.EventMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.superid.webapp.notice.proto.Message.EventMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.superid.webapp.notice.proto.Message.EventMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cn.superid.webapp.notice.proto.Message.EventMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cn.superid.webapp.notice.proto.Message.EventMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cn.superid.webapp.notice.proto.Message.EventMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cn.superid.webapp.notice.proto.Message.EventMsg prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cn.superid.webapp.notice.proto.EventMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cn.superid.webapp.notice.proto.EventMsg)
        cn.superid.webapp.notice.proto.Message.EventMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_EventMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_EventMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cn.superid.webapp.notice.proto.Message.EventMsg.class, cn.superid.webapp.notice.proto.Message.EventMsg.Builder.class);
      }

      // Construct using cn.superid.webapp.notice.proto.Message.EventMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        eventType_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        affairId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        groupId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        userId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.superid.webapp.notice.proto.Message.internal_static_cn_superid_webapp_proto_EventMsg_descriptor;
      }

      public cn.superid.webapp.notice.proto.Message.EventMsg getDefaultInstanceForType() {
        return cn.superid.webapp.notice.proto.Message.EventMsg.getDefaultInstance();
      }

      public cn.superid.webapp.notice.proto.Message.EventMsg build() {
        cn.superid.webapp.notice.proto.Message.EventMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cn.superid.webapp.notice.proto.Message.EventMsg buildPartial() {
        cn.superid.webapp.notice.proto.Message.EventMsg result = new cn.superid.webapp.notice.proto.Message.EventMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.eventType_ = eventType_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.affairId_ = affairId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.groupId_ = groupId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.userId_ = userId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.superid.webapp.notice.proto.Message.EventMsg) {
          return mergeFrom((cn.superid.webapp.notice.proto.Message.EventMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cn.superid.webapp.notice.proto.Message.EventMsg other) {
        if (other == cn.superid.webapp.notice.proto.Message.EventMsg.getDefaultInstance()) return this;
        if (other.hasType()) {
          bitField0_ |= 0x00000001;
          type_ = other.type_;
          onChanged();
        }
        if (other.hasEventType()) {
          setEventType(other.getEventType());
        }
        if (other.hasAffairId()) {
          setAffairId(other.getAffairId());
        }
        if (other.hasGroupId()) {
          setGroupId(other.getGroupId());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasType()) {
          return false;
        }
        if (!hasEventType()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cn.superid.webapp.notice.proto.Message.EventMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cn.superid.webapp.notice.proto.Message.EventMsg) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object type_ = "";
      /**
       * <code>required string type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string type = 1;</code>
       */
      public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            type_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>required string type = 1;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }

      private int eventType_ ;
      /**
       * <code>required uint32 eventType = 2;</code>
       */
      public boolean hasEventType() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 eventType = 2;</code>
       */
      public int getEventType() {
        return eventType_;
      }
      /**
       * <code>required uint32 eventType = 2;</code>
       */
      public Builder setEventType(int value) {
        bitField0_ |= 0x00000002;
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 eventType = 2;</code>
       */
      public Builder clearEventType() {
        bitField0_ = (bitField0_ & ~0x00000002);
        eventType_ = 0;
        onChanged();
        return this;
      }

      private long affairId_ ;
      /**
       * <code>optional uint64 affairId = 3;</code>
       */
      public boolean hasAffairId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional uint64 affairId = 3;</code>
       */
      public long getAffairId() {
        return affairId_;
      }
      /**
       * <code>optional uint64 affairId = 3;</code>
       */
      public Builder setAffairId(long value) {
        bitField0_ |= 0x00000004;
        affairId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 affairId = 3;</code>
       */
      public Builder clearAffairId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        affairId_ = 0L;
        onChanged();
        return this;
      }

      private long groupId_ ;
      /**
       * <code>optional uint64 groupId = 4;</code>
       */
      public boolean hasGroupId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional uint64 groupId = 4;</code>
       */
      public long getGroupId() {
        return groupId_;
      }
      /**
       * <code>optional uint64 groupId = 4;</code>
       */
      public Builder setGroupId(long value) {
        bitField0_ |= 0x00000008;
        groupId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 groupId = 4;</code>
       */
      public Builder clearGroupId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        groupId_ = 0L;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>optional uint64 userId = 5;</code>
       */
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional uint64 userId = 5;</code>
       */
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>optional uint64 userId = 5;</code>
       */
      public Builder setUserId(long value) {
        bitField0_ |= 0x00000010;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 userId = 5;</code>
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000010);
        userId_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:cn.superid.webapp.notice.proto.EventMsg)
    }

    // @@protoc_insertion_point(class_scope:cn.superid.webapp.notice.proto.EventMsg)
    private static final cn.superid.webapp.notice.proto.Message.EventMsg DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cn.superid.webapp.notice.proto.Message.EventMsg();
    }

    public static cn.superid.webapp.notice.proto.Message.EventMsg getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<EventMsg>
        PARSER = new com.google.protobuf.AbstractParser<EventMsg>() {
      public EventMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new EventMsg(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventMsg> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventMsg> getParserForType() {
      return PARSER;
    }

    public cn.superid.webapp.notice.proto.Message.EventMsg getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_superid_webapp_proto_NoticeMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_superid_webapp_proto_NoticeMsg_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cn_superid_webapp_proto_EventMsg_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_cn_superid_webapp_proto_EventMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rmessage.proto\022\027cn.superid.webapp.proto" +
      "\"\274\001\n\tNoticeMsg\022\014\n\004type\030\001 \002(\t\022\017\n\007subType\030" +
      "\002 \001(\t\022\023\n\013displayName\030\003 \001(\t\022\022\n\nfromUserId" +
      "\030\004 \001(\004\022\020\n\010toUserId\030\005 \001(\004\022\020\n\010toRoleId\030\006 \001" +
      "(\004\022\020\n\010affairId\030\007 \001(\004\022\021\n\trelatedId\030\010 \001(\004\022" +
      "\r\n\005state\030\t \001(\r\022\017\n\007content\030\n \001(\t\"^\n\010Event" +
      "Msg\022\014\n\004type\030\001 \002(\t\022\021\n\teventType\030\002 \002(\r\022\020\n\010" +
      "affairId\030\003 \001(\004\022\017\n\007groupId\030\004 \001(\004\022\016\n\006userI" +
      "d\030\005 \001(\004B\tB\007Message"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cn_superid_webapp_proto_NoticeMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cn_superid_webapp_proto_NoticeMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_superid_webapp_proto_NoticeMsg_descriptor,
        new java.lang.String[] { "Type", "SubType", "DisplayName", "FromUserId", "ToUserId", "ToRoleId", "AffairId", "RelatedId", "State", "Content", });
    internal_static_cn_superid_webapp_proto_EventMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cn_superid_webapp_proto_EventMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_cn_superid_webapp_proto_EventMsg_descriptor,
        new java.lang.String[] { "Type", "EventType", "AffairId", "GroupId", "UserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
